# Generated by Django 5.1.4 on 2025-01-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='timestamp',
            new_name='visited_at',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='location',
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country_code',
            field=models.CharField(default='Not available', max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='hostname',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='organisation',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='postal_code',
            field=models.CharField(default='Not available', max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='region',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='timezone',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
