# Generated by Django 5.1.4 on 2025-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracking', '0002_rename_timestamp_visitor_visited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
