# Generated by Django 5.1.4 on 2025-01-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracking', '0003_alter_visitor_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
